### ISSUE TITLE
Project does not build.

### ISSUE THREAD

**Issue by sub37** [malako/sensorpush-core#5]
This project does not build.  7 errors like below.

Error	CS0579	Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute	Mrc.SensorPushCore	\GitHub\sensorpush-core\obj\Debug\netstandard2.1\Mrc.SensorPushCore.AssemblyInfo.cs	14	Active

**Comment by malako** [comment]
Turns out later versions of VS handles assembly info differently. I fixed it by disabling auto generated assembly info in the csproj file. Nuget packages are updated as well.

Let me know if it works out for you.

**Comment by malako** [comment]
Closing this
